# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Values for registry1 flavor

# Example variables from UDS package repo template. Update to relevant variables after templating
image:
  repository: registry1.dso.mil/ironbank/radiusmethod/socketzero/receiver
  tag: 0.7.0
